language: minimal
sudo: required
services:
  - docker
before_script:
  - curl -L https://github.com/buildkite/cli/releases/download/v0.2.0/bk-linux-amd64-0.2.0 > bk
  - chmod +x bk
  - sudo mv bk /usr/local/bin/bk
script:
  # Run all the steps defined in .buildkite/pipeline.yml
  bk run